Restaurante/Models/Reserva.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Reserva
    {
        [Display(Name = "Codigo de reserva")]
        public int IdReserva { get; set; }
        [Display(Name = "Nombre de Usuario")]
        public string NombreUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        [Display(Name = "Sede")]
        public int IdSede { get; set; }
        public int Cantidad { get; set; }
        public string Correo { get; set; }
        [Display(Name = "Sede")]
        public virtual Sede Sede { get; set; }
    }
}

Restaurante/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Restaurante.Models;
using RestSharp;
using RestSharp.Authenticators;

namespace Restaurante.Controllers
{
    public class ReservasController : Controller
    {
        public string Mensaje { get; set; }
        public string Estilo { get; set; }


        private RestauranteEntities db = new RestauranteEntities();

        // GET: Reservas
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var reserva = db.Reserva.Include(r => r.Sede);
            return View(await reserva.ToListAsync());
        }

        // GET: Reservas/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = await db.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            return View(reserva);
        }

        // GET: Reservas/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede");
            return View();
        }

        // POST: Reservas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<ActionResult> Create([Bind(Include = "IdReserva,NombreUsuario,Fecha,IdSede,Cantidad,Correo")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                db.Reserva.Add(reserva);
                await db.SaveChangesAsync();
                SendSimpleMessage(reserva);
                if (User.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
                
            }

            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede", reserva.IdSede);
            return View(reserva);
        }

        // GET: Reservas/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = await db.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede", reserva.IdSede);
            return View(reserva);
        }

        // POST: Reservas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "IdReserva,NombreUsuario,Fecha,IdSede,Cantidad,Correo")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reserva).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede", reserva.IdSede);
            return View(reserva);
        }

        // GET: Reservas/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = await db.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            return View(reserva);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Reserva reserva = await db.Reserva.FindAsync(id);
            db.Reserva.Remove(reserva);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public static void SendSimpleMessage(Reserva reserva)
        {
            RestauranteEntities db = new RestauranteEntities();
            RestClient client = new RestClient();
            System.Uri uri = new System.Uri("https://api.mailgun.net/v3");
            client.BaseUrl = uri;
            client.Authenticator =
                   new HttpBasicAuthenticator("api",
                                              "key-05394996027f04202e30a49f7d6ea57a");
            RestRequest request = new RestRequest();
            request.AddParameter("domain",
                                "sandbox2a19a8beb07d48279eecf180fe4f0d62.mailgun.org", ParameterType.UrlSegment);
            request.Resource = "{domain}/messages";
            request.AddParameter("from", "Equipo Restaurante <postmaster@sandbox2a19a8beb07d48279eecf180fe4f0d62.mailgun.org>");
            request.AddParameter("to", reserva.NombreUsuario + " " + "<" + reserva.Correo + ">");
            request.AddParameter("subject", "Reserva en el Restaurante para: " + reserva.NombreUsuario);
            request.AddParameter("text", "Has realizado una reserva en el restaurante\nDatos de la reserva:\n\tA nombre de: " + reserva.NombreUsuario + "\n\tCódigo reserva: " + reserva.IdReserva + "\n\tFecha reserva: " + reserva.Fecha + "\n\tSede: " + db.Sede.FirstOrDefault(x => x.IdSede.Equals(reserva.IdSede)).NombreSede + "\nRecuerde que el código de la reserva es indispensable para el ingreso.\nPara mayores informes llamar al 01-8000-117711");
            request.Method = Method.POST;
            client.Execute(request);
        }
    }
}

Restaurante/Controllers/SedesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Restaurante.Models;

namespace Restaurante.Controllers
{
    [Authorize]
    public class SedesController : Controller
    {
        private RestauranteEntities db = new RestauranteEntities();

        // GET: Sedes
        public async Task<ActionResult> Index()
        {
            return View(await db.Sede.ToListAsync());
        }

        // GET: Sedes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sede sede = await db.Sede.FindAsync(id);
            if (sede == null)
            {
                return HttpNotFound();
            }
            return View(sede);
        }

        // GET: Sedes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sedes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IdSede,NombreSede")] Sede sede)
        {
            if (ModelState.IsValid)
            {
                db.Sede.Add(sede);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sede);
        }

        // GET: Sedes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sede sede = await db.Sede.FindAsync(id);
            if (sede == null)
            {
                return HttpNotFound();
            }
            return View(sede);
        }

        // POST: Sedes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IdSede,NombreSede")] Sede sede)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sede).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sede);
        }

        // GET: Sedes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sede sede = await db.Sede.FindAsync(id);
            if (sede == null)
            {
                return HttpNotFound();
            }
            return View(sede);
        }

        // POST: Sedes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Sede sede = await db.Sede.FindAsync(id);
            db.Sede.Remove(sede);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Restaurante/Views/Reservas/Create.cshtml
@model Restaurante.Models.Reserva

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reserva</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NombreUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div class='input-group date' id='datetimepicker1'>
                    @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "datetimepicker form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdSede, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdSede", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdSede, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

   
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Restaurante/Views/Reservas/Delete.cshtml
@model Restaurante.Models.Reserva

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede.NombreSede)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede.NombreSede)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Restaurante/Views/Reservas/Details.cshtml
@model Restaurante.Models.Reserva

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede.NombreSede)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede.NombreSede)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdReserva }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Restaurante/Views/Reservas/Edit.cshtml
@model Restaurante.Models.Reserva

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reserva</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdReserva)

        <div class="form-group">
            @Html.LabelFor(model => model.NombreUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <div class='input-group date' id='datetimepicker1'>
                    @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "datetimepicker form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.IdSede, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdSede", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdSede, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Restaurante/Views/Reservas/Index.cshtml
@model IEnumerable<Restaurante.Models.Reserva>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

    <div class="btn-group btn-group-justified">
       
            @Html.ActionLink("Crear nueva reserva", "Create", null, new { @class = "btn btn-primary btn-large" })
            @Html.ActionLink("Administrar Sedes", "Index", "Sedes", null, new { @class = "btn btn-primary btn-large" })
            @Html.ActionLink("Registrar Administrador", "Register", "Account", null, new { @class = "btn btn-primary btn-large" })
        
        
    </div>
    <br>
    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdReserva)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sede)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdReserva)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreUsuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Correo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sede.NombreSede)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.IdReserva }) |
                    @Html.ActionLink("Details", "Details", new { id = item.IdReserva }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.IdReserva })
                </td>
            </tr>
        }

    </table>