Restaurante/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Restaurante.Models;
using RestSharp;
using RestSharp.Authenticators;

namespace Restaurante.Controllers
{
    public class ReservasController : Controller
    {
        public string Mensaje { get; set; }
        public string Estilo { get; set; }


        private RestauranteEntities db = new RestauranteEntities();

        // GET: Reservas
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var reserva = db.Reserva.Include(r => r.Sede);
            return View(await reserva.ToListAsync());
        }

        // GET: Reservas/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = await db.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            return View(reserva);
        }

        // GET: Reservas/Create
        [AllowAnonymous]
        public ActionResult Create()
        {
            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede");
            return View();
        }

        // POST: Reservas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<ActionResult> Create([Bind(Include = "IdReserva,NombreUsuario,Fecha,IdSede,Cantidad,Correo")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                db.Reserva.Add(reserva);
                await db.SaveChangesAsync();
                SendSimpleMessage(reserva);
                if (User.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
                
            }

            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede", reserva.IdSede);
            return View(reserva);
        }

        // GET: Reservas/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = await db.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede", reserva.IdSede);
            return View(reserva);
        }

        // POST: Reservas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "IdReserva,NombreUsuario,Fecha,IdSede,Cantidad,Correo")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reserva).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdSede = new SelectList(db.Sede, "IdSede", "NombreSede", reserva.IdSede);
            return View(reserva);
        }

        // GET: Reservas/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reserva reserva = await db.Reserva.FindAsync(id);
            if (reserva == null)
            {
                return HttpNotFound();
            }
            return View(reserva);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Reserva reserva = await db.Reserva.FindAsync(id);
            db.Reserva.Remove(reserva);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public static void SendSimpleMessage(Reserva reserva)
        {
            RestauranteEntities db = new RestauranteEntities();
            RestClient client = new RestClient();
            System.Uri uri = new System.Uri("https://api.mailgun.net/v3");
            client.BaseUrl = uri;
            client.Authenticator =
                   new HttpBasicAuthenticator("api",
                                              "key-05394996027f04202e30a49f7d6ea57a");
            RestRequest request = new RestRequest();
            request.AddParameter("domain",
                                "sandbox2a19a8beb07d48279eecf180fe4f0d62.mailgun.org", ParameterType.UrlSegment);
            request.Resource = "{domain}/messages";
            request.AddParameter("from", "Equipo Restaurante <postmaster@sandbox2a19a8beb07d48279eecf180fe4f0d62.mailgun.org>");
            request.AddParameter("to", reserva.NombreUsuario + " " + "<" + reserva.Correo + ">");
            request.AddParameter("subject", "Reserva en el Restaurante para: " + reserva.NombreUsuario);
            request.AddParameter("text", "Has realizado una reserva en el restaurante\nDatos de la reserva:\n\tA nombre de: " + reserva.NombreUsuario + "\n\tCódigo reserva: " + reserva.IdReserva + "\n\tFecha reserva: " + reserva.Fecha + "\n\tSede: " + db.Sede.FirstOrDefault(x => x.IdSede.Equals(reserva.IdSede)).NombreSede + "\nRecuerde que el código de la reserva es indispensable para el ingreso.\nPara mayores informes llamar al 01-8000-117711");
            request.Method = Method.POST;
            client.Execute(request);
        }
    }
}

Restaurante/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación RESTAURANTE</title>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
    <link rel="stylesheet" type="text/css" media="screen" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet">
    
    
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript">
                $(function () {
                    $('#datetimepicker1').datetimepicker({
                        format: 'lll'
                    });
                });

    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @using Microsoft.AspNet.Identity
                @if (Request.IsAuthenticated)
                {
                   
                    @Html.ActionLink("Administración", "Index", "Reservas", new { area = "" }, new { @class = "navbar-brand" })

                }
                else
                {
                    @Html.ActionLink("Reservas", "Create", "Reservas", new { area = "" }, new { @class = "navbar-brand" })

                }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                       
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación RESTAURANTE</p>
        </footer>
    </div>

</body>
</html>